version: '3'

services:
  db:
    container_name: db
    image: mysql:8.0.32-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=togooddb

  pma:
    container_name: pma
    image: phpmyadmin:5.2.1
    ports:
      - 8080:80
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    
  svr:
    container_name: svr
    build: .
    ports:
      - 8000:8000
